Blog app: add devise
lerfast/blog-app pull request #9
Opened 2023-11-08 18:17 UTC by lerfast

Hello fellow code reviewer, we did the following:

 Remove current_user method in ApplicationController, devise will provide us with one.
 [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
 Can register a new user.
 User logs in with a combination of email and password.
 Hashed password should be stored in the database.
 Ask for confirmation of email.
 Can reset password.

2023-11-08 19:25 UTC, cynthiainga requested changes
Hi @lerfast, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] The `current_user` method in `ApplicationController` has been removed ✔️ 
- [ ] Devise has been installed and setup ✔️ 
- [ ] The application allows for registering a new user ✔️ 
- [ ] A user can log in with a combination of email and password ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comment under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 19:25 UTC, cynthiainga commented on app/views/layouts/application.html.erb
- [ ] As mentioned in the project requirements the registration and login should be modified to match the wireframes, kindly fix the design 🙃 😁 

Your design

<img width="391" alt="Screenshot 2023-11-08 at 21 48 27" src="https://github.com/lerfast/blog-app/assets/74501523/eddb67be-619a-430e-b7ed-ad4adc23a852">

Given wireframe

<img width="431" alt="Screenshot 2023-11-08 at 21 51 05" src="https://github.com/lerfast/blog-app/assets/74501523/3a0f7952-f051-4ed1-a5e9-80edd378f432">

2023-11-08 21:55 UTC, lerfast commented on app/views/layouts/application.html.erb
I did my best effort
![image](https://github.com/lerfast/blog-app/assets/111823606/a97f027d-19d8-4544-b1e6-8601c6cb832f)

2023-11-09 01:19 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @lerfast, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Gitflow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 14:20 UTC, merged